### ISSUE TITLE
2.0 版本组件开发

### ISSUE THREAD

**Issue by eyunhua** [ecomfe/veui-theme-blue#108]
> 提示类
- [x] Alert（固定提示框）@eyunhua
- [x]  AlertBox（弹框提示框）@eyunhua
- [x]  Badge（徽标）@eyunhua
- [x] Toast（全局提示框）@wangkaifang
- [x] Tooltip（tooltip提示）@wangkaifang
- [x]  Popover（元素上弹窗）@wangkaifang
- [x] Tag（标签）@profitfrl

> 按钮类
- [x] Button（按钮）@weishuping
- [x] ButtonGroup（组合按钮）@weishuping
- [x] Checkbox（复选框）@weishuping
- [x] CheckButtonGroup（复选组合按钮）@weishuping
- [x] CheckboxGroup（复选组合）@weishuping
- [x] Radio（单选框）@RookieFirstFly
- [x] RadioButtonGroup（单选按钮组合）@RookieFirstFly
- [x] RadioGroup（单选框组合）@RookieFirstFly
- [x] Breadcrumb（面包屑）@profitfrl
- [x] Link（超链接）@fuchunhui

> 输入类
- [x] Autocomplete（模糊检索下拉框）@CuteSunLee
- [x] Input（输入框）@CuteSunLee
- [x] InputGroup（组合输入框）@CuteSunLee
- [x] SearchBox（搜索框）@CuteSunLee
- [x] Textarea（文本域）@CuteSunLee
- [x] NumberInput（数字输入框）@CuteSunLee
- [x] Dropdown（下拉框）@eyunhua
- [x] Select（下拉框）@eyunhua

> 日期类
- [x] Calendar（日历）@Atlas-lili
- [x] DatePicker（日期选择）@Atlas-lili
- [x] TimePicker（时间选择）@fuchunhui

> 浮层类
- [x] Dialog（弹框）@weishuping
- [x] Drawer（抽屉）@fengzhike 
- [ ] Overlay（浮层）@eyunhua
- [ ] Embedded（嵌入式的模态区域）@eyunhua

> 页面布局类
- [x] Anchor（锚点定位）@fuchunhui
- [x] Carousel（轮播图）@eyunhua
- [x] Collapse（折叠）@eyunhua
- [x] Grid（栅格布局）@RookieFirstFly
- [x] Loading（加载中）@profitfrl
- [x] Menu（菜单）@weishuping
- [ ] Nav（菜单）@eyunhua
- [ ] Progress（进度条）@eyunhua
- [ ] Icon（图标）@eyunhua
- [x] Form（表单）@eyunhua

> 表格类
- [x] Table（表格）@eyunhua
- [x] Pagination（分页）@eyunhua

> 树形类
- [x] Transfer（穿梭框）@eyunhua
- [x] Tree（树形）@eyunhua

> 上传
- [x] Uploader（上传）@eyunhua

> 切换类
- [x] Slider（滑杆）@Atlas-lili
- [x] Steps（步骤条）@Atlas-lili
- [x] Switch（开关）@RookieFirstFly
- [ ] Tabs（选项卡）@eyunhua

**Comment by RookieFirstFly** [comment]
栅格布局样式
Switch 开关样式
Radio、RadioButtonGroup、RadioGroup 单选按钮样式
--王印

**Comment by fuchunhui** [comment]
timepicker link

**Comment by profitfrl** [comment]
Toast  Tag  Loading  Menu  Progress

**Comment by CuteSunLee** [comment]
输入类 1 2 3 4

**Comment by weishuping** [comment]
按钮类 12345

**Comment by weishuping** [comment]
浮层类 Dialog（弹框）

**Comment by xiguapi211** [comment]
Dropdown（下拉框）
 Select（下拉框）

**Comment by sohucw** [comment]
Transfer（穿梭框）
 Tree（树形）

**Comment by fuchunhui** [comment]
Calendar（日历）
 DatePicker（日期选择）
指派@Atlas-lili （王钦）

**Comment by fengzhike** [comment]
Drawer（抽屉）

**Comment by Atlas-lili** [comment]
Calendar（日历）
DatePicker（日期选择）
Slider（滑杆）
 Steps（步骤条）
--王钦
