### ISSUE TITLE
组件之间样式未统一

### ISSUE THREAD

**Issue by Domy** [ecomfe/veui-theme-blue#40]
![image](https://user-images.githubusercontent.com/3655223/38660143-d103dd6c-3e5e-11e8-9b5b-4bb1f665131a.png)
![image](https://user-images.githubusercontent.com/3655223/38660313-601cc446-3e5f-11e8-8e21-0473b7f4701a.png)
1. 同一个input组件，输入文字的字号和placehoder的字号不一致；

![image](https://user-images.githubusercontent.com/3655223/38660152-d6c3e06c-3e5e-11e8-9515-0ee71e315d1b.png)
2. input 和 searchbox 的holder也不一样

是不是css中有配置文件可以统一改？如果一个组件一个组件改容易有遗漏

**Comment by eyunhua** [comment]
已修复
