### ISSUE TITLE
pagination组件样式与设计稿不统一

### ISSUE THREAD

**Issue by fuchunhui** [ecomfe/veui-theme-blue#41]
![machi 2018-04-13 14-36-47](https://user-images.githubusercontent.com/29879262/38720316-65f3759e-3f28-11e8-814d-f2e6933e1d98.png)
![machi 2018-04-13 14-37-05](https://user-images.githubusercontent.com/29879262/38720317-6646c514-3f28-11e8-8108-830ba26c608a.png)

**Comment by fuchunhui** [comment]
1.active状态和hover均没有border
2.pre和next按钮之间的空隙和数字之间是一样的，都是8px.
3.1位数的时候，数字按钮的Width是28px.

**Comment by fuchunhui** [comment]
4.font-size:12px;

**Comment by eyunhua** [comment]
1位数的时候，数字按钮的Width是28px，这个目前遇到了点疑问，随后沟通后再改，其他1、2、4已修复
