### ISSUE TITLE
data-picker组件样式与交互稿不一致，差别较大

### ISSUE THREAD

**Issue by fuchunhui** [ecomfe/veui-theme-blue#42]
![machi 2018-04-13 18-46-01](https://user-images.githubusercontent.com/29879262/38730896-efae5232-3f4a-11e8-95bf-60a6cba5c6f7.png)
涉及到较多的点不一致

**Comment by eyunhua** [comment]
灰色背景小红点和默认情况下小蓝点的使用情况不明确，随后跟设计确认后再看是否修改

**Comment by fuchunhui** [comment]
UI同学后续会系统更新规范文档，我们按照最新文档调整。
