### ISSUE TITLE
blue适应veui到14版本时，补充一些hulk中遇到的注意点

### ISSUE THREAD

**Issue by fuchunhui** [ecomfe/veui-theme-blue#55]
1.breadcrumbitem
next 更改为 separator

2.calendar组件的年月选择

3.input的placeholder变化，错位问题。
![machi 2018-06-19 17-31-09](https://user-images.githubusercontent.com/29879262/41589252-9dfe7a7c-73e6-11e8-97bc-d798fa275328.png)
主要是input的height不是默认值28的时候，会出现错位问题，皮肤里需要做到更好的兼容，避免使用时的重复书写

**Comment by eyunhua** [comment]
问题1、2已修改，3 input有不同的ui大小，如果需自定义大小，可自行设置width、height和line-height进行定义
